### ISSUE TITLE
[REQUEST] Several Google calendars

### ISSUE THREAD

**Issue by k0nte** [indifyco/Feature-Requests#10]
It would be great to be able to have several calendars in one view. They should have different coulours, so probably it's easiest to just fetch the colours from Google calendar.

**Comment by courtniac** [comment]
Hi! Yesterday we released this feature as part of the Google Calendar pro plan :) Check out our FB community for a discount code and to share what you think!

**Comment by saritag2020** [comment]
@courtniac or any other collars I have had a request to the FB outstanding for a while with no response. I just canceled and resent!
