### ISSUE TITLE
[ENHANCEMENT] Add Quarter to Life Progress Bar Widget

### ISSUE THREAD

**Issue by medsaadnaji** [indifyco/Feature-Requests#13]

**Comment by indify-co** [comment]
Hi @medsaadnaji! Do you mind elaborating on this request? 😁

**Comment by medsaadnaji** [comment]
Hi, I hope that you add a progress bar to quarters the same way you did
with month and year, like right now we are in the the 10th month of 2020,
so it's the last quarter of 2020 (q4), approximately 50% of q4.

**Comment by JoshMoxey** [comment]
+1, I found myself looking for this today as I move into a more quarter based goal setting mindset

**Comment by indify-co** [comment]
@medsaadnaji @JoshMoxey Great news, we just launched this feature! You'll just need to go to the widget's configure page to enable it. Let us know if you have any feedback! ✨
