### ISSUE TITLE
[REQUEST] Gantt chart from table

### ISSUE THREAD

**Issue by glebov** [indifyco/Feature-Requests#2]
Widget, which generates gantt chart from my notion table.

**Comment by indify-co** [comment]
Allegedly Notion is releasing their own version of a Gantt chart! 🔥

**Comment by indify-co** [comment]
Just kidding – looks like it was posted on July of last year! https://twitter.com/NotionHQ/status/1156685970969788423

Will raise priority to high 👍

**Comment by courtniac** [comment]
It looks like Notion granted your wish! 😮 https://twitter.com/NotionHQ/status/1326571876093579264?s=20
