### ISSUE TITLE
[BUG] Email Id , Date of Birth and Other Things are Leaked in Progress Bar Source Code.

### ISSUE THREAD

**Issue by KeerthiNaathan** [indifyco/Feature-Requests#21]
Today I was doing some colour customization in my widget using inspection (Feature request), but I found my email id, date of birth is visible from the source code.
![image](https://user-images.githubusercontent.com/55060041/98248325-c8401680-1f9a-11eb-8109-123c2b4a8c18.png)
I Snipping the Code for Better 
```<script id="__NEXT_DATA__" type="application/json">
            {"props":{"pageProps":{"widgetPrefs":{"dateOfBirth":"MM/DD/YYYY","title":"Untitled","dateCreated":"2020-10-27T16:43:55.378Z","darkModeHoverBar":true,"selectedBars":["year","month","day","life"],"darkMode":true,"livingUntilAge":82}},"urlInfo":{"protocol":"https:","host":"indify.co","origin":"https://indify.co"},"user":{"uid":"GAJQecw0K6bRvdCYBAR2mgLBRXx1","email":"emailid@usedtologin.com"},"userData":{"position":26701,"email":"emailid@usedtologin.com","enabledWidgets":[],"mailchimp":{"email_type":"","unique_email_id":"","web_id":"","language":"","status":"","id":""},"widgetPrefs":{"calendar":["7YhEPEfDeRdxxxxxxxxx"],"clock":["5DcQqtkYP9K7OANRkLvB","s7syjUnY0sLvF5gaCT80"],"progressBar":["znuwzuW7LqD0UqZ6XLaA"]},"stripe":{"subscriptionStatus":"not_activated_yet","customerId":"cus_IHUAv7RaNxxxxx","subscriptionId":""},"created":"2020-10-27T16:38:19.769Z"}},"page":"/widgets/live/progressBar/[progressBarPrefsId]","query":{"progressBarPrefsId":"znuwzuW7LqDxxxxxxxxx"},"buildId":"jFuEyN5d5xSD-0nN1ztl-","runtimeConfig":{},"nextExport":false,"isFallback":false,"gip":true,"appGip":true}
        </script> 
```

Here i edited some of my personal information, but here thing, your email id, date you created the account, date of birth, status of the account, account no and other things.
I made the post in reddit, some comment suggest to contact you directly.
So kindly Take Action.

**Comment by indify-co** [comment]
Hi @KeerthiNaathan, thanks for reporting this bug to us! We can confirm that this is not a leak, rather it's your session data since you're logged in. 

We've shared more context on the issue on [Reddit](https://www.reddit.com/r/Notion/comments/joi05q/if_you_are_using_indifyco_progress_bar_your_email/gb92tyg?utm_source=share&utm_medium=web2x&context=3): 
>I want to explain what's doing on above – if you're logged in to your Indify account, your data will be loaded on Indify's pages, as you see above. This includes your email, for example.
>
>However, if you log out, or visit this widget link on a different browser / incognito mode, this data will no longer be available, since you are no longer logged in.
>
>Therefore, if others visit this link, they won't be able to view this information – only you will! However, we love to hear your concerns since we care a lot about privacy, and hope to make this a safe platform for everyone to use.
>
>Please don't hesitate to reach out if you find any other issues and we'll work on fixing them asap :)
>
>Hope this clears up any confusion!
