### ISSUE TITLE
[ENHANCEMENT] Custom Colour Changing in Widget

### ISSUE THREAD

**Issue by KeerthiNaathan** [indifyco/Feature-Requests#22]
I was using notion-enhancer theme and everything was ok because of widget as it only support 2 colours (dark and light theme).

Example:
This is My Homepage, everything is purple and their associates except the widget. 
![image](https://user-images.githubusercontent.com/55060041/98249227-068a0580-1f9c-11eb-9031-acb1d41d3e74.png)

So I played with inspection css for showing the outcome that i required
![image](https://user-images.githubusercontent.com/55060041/98249453-418c3900-1f9c-11eb-8b36-fe4b4a100988.png)

My request is 
- Colour Customization using RGB Mix for Background as well the Front.
- Colour Customization Default Template 

Thanks

**Comment by courtniac** [comment]
Hi @KeerthiNaathan! We recently added an easter egg you might enjoy. Just click on the 😄 face by your username when you're logged in on Indify, and you'll have access to Advanced CSS Styling– meaning you can customize the colors of your widgets to your liking 🎉 If you have any more questions in general or about CSS, we're happy to answer!
