### ISSUE TITLE
[REQUEST] Google/Microsoft Tasks / Reminders

### ISSUE THREAD

**Issue by fredrikj31** [indifyco/Feature-Requests#24]
Hi.

I have an idea to add a Google reminder, where you also can check out your tasks, and if you can follow your theme I think it would be a great widget.

If you have any questions about the widget, feel free to ask in this issue.

- Fredrik Johansen :)

**Comment by indify-co** [comment]
Hi @fredrikj31! Thanks for submitting this request :) We have a similar ticket open for Google tasks, is this what you mean? (https://github.com/indifyco/Feature-Requests/issues/7)

**Comment by fredrikj31** [comment]
I think I meant Google Tasks. It would be nice to have a widget like that, so its synced with a Google calendar. So yes I meant Google Tasks. My bad. But nice to hear that it's already a request. Looking forward to use it :)

**Comment by fredrikj31** [comment]
But if you could add a feature, so you can check them off when they are done. That feature to the Google Task would be nice to have.

**Comment by indify-co** [comment]
Adding onto this thread – another great addition would be microsoft tasks!

**Comment by fredrikj31** [comment]
Totally. I think most of the users either use Google Tasks or Microsoft Tasks. So it would be awesome to add that!
