### ISSUE TITLE
[BUG] `Week` progress bar shows negative percentages

### ISSUE THREAD

**Issue by brandonteo** [indifyco/Feature-Requests#42]
I noticed lately that whenever I get to Sunday the progress bar percentages will show up as negative numbers. The actual bar looks correct but the percentage seems janky.

<img width="418" alt="Screen Shot 2021-05-02 at 4 59 28 PM" src="https://user-images.githubusercontent.com/16714410/116819420-f2e4e380-ab67-11eb-9019-bb150b9d1b3b.png">

**Comment by indify-co** [comment]
Update has been pushed, and this issue should be fixed! Please comment if this issue persists @brandonteo, and thanks for letting us know :)
