### ISSUE TITLE
[ENHANCEMENT] Weather widget using too much CPU

### ISSUE THREAD

**Issue by zlhaa23** [indifyco/Feature-Requests#5]
The weather widget has very high CPU and GPU usage. It happens even when Notion is minimized (Windows), and causes continuous fan noise. Apparently it is due to the CSS animation for the weather icon. Please consider a less resource-intensive implementation. It is not worth 20% CPU in the background just to have a nice rotating sun.

**Comment by courtniac** [comment]
I just added this enhancement to the weather widget; thank you for submitting a request! 

https://www.notion.so/What-s-New-66f5da57d72a4a8a96cff215045fd7e5
