### ISSUE TITLE
[BUG] Countdown Widget

### ISSUE THREAD

**Issue by daybreak3** [indifyco/Feature-Requests#56]
Having issues with the date and time. 
![2021-10-25](https://user-images.githubusercontent.com/93135987/138699962-88ff904e-6f8e-45bb-a89b-e7425aa2c8dd.png)

I can't set the countdown date correctly. Today is Oct 25, I wanted to set a countdown to December 17 but it only says 22 days. It's supposed to be 53 days

**Comment by 101lols** [comment]
It's saying 1 month and 22 days.

**Comment by indify-co** [comment]
Hi @daybreak3! If you'd like it to say 53 days, you can uncheck the "month" toggle :)

**Comment by indify-co** [comment]
Closing for now because this appears to be resolved!
