### ISSUE TITLE
[ENHANCEMENT] Would be nice if you could Order the Progress Bars, e.g i prefer to have it Day, Month, Year, Life 

### ISSUE THREAD

**Issue by Serity95** [indifyco/Feature-Requests#6]
Yeah the Title pretty much says it. 
I dont like the American Format to much. 

Thanks and keep up the Good Work!

**Comment by indify-co** [comment]
Hi @Serity95! Happy to announce that we've shipped this feature! Feel free to check it out on indify.co :)
