### ISSUE TITLE
[ENHANCEMENT] Can change colors of widgets other than white and dark mode

### ISSUE THREAD

**Issue by beatricetotanes** [indifyco/Feature-Requests#9]

**Comment by courtniac** [comment]
Hi @beatricetotanes! We recently added an easter egg you might enjoy. Just click on the 😄 face by your username when you're logged in on Indify, and you'll have access to Advanced CSS Styling– meaning you can customize the colors of your widgets to your liking 🎉 If you have any more questions in general or about CSS, we're happy to answer!
